// frontend/src/services/productServices.ts
import { Product } from "@/types/product";
import { useAuth } from "@/context/AuthContext"; // Import useAuth to get the token

const API_BASE_URL = import.meta.env.VITE_BACKEND_URL;

// ===========================================
// Public Functions (No Token Needed)
// ===========================================

// GET ALL Products
export const fetchProducts = async (): Promise<Product[]> => {
  const response = await fetch(`${API_BASE_URL}/api/products`);
  if (!response.ok) {
    throw new Error(`Failed to fetch products: ${response.statusText}`);
  }
  return response.json();
};

// GET A SINGLE Product
export const fetchProductById = async (id: string): Promise<Product> => {
  const response = await fetch(`${API_BASE_URL}/api/products/${id}`);
  if (!response.ok) {
    if (response.status === 404) {
      throw new Error("Product not found");
    }
    throw new Error(
      `Failed to fetch product with ID ${id}: ${response.statusText}`
    );
  }
  return response.json();
};

// ===========================================
// Protected Functions (Token Required)
// ===========================================

// CREATE A Product
export const createProduct = async (
  // The product data to create. Omit fields generated by the backend.
  productData: Omit<Product, "_id" | "createdAt" | "updatedAt">,
  // The JWT token for authorization.
  token: string
): Promise<Product> => {
  const response = await fetch(`${API_BASE_URL}/api/products`, {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      // Include the token in the Authorization header.
      Authorization: `Bearer ${token}`,
    },
    body: JSON.stringify(productData),
  });

  if (!response.ok) {
    // Try to parse the error message from the backend.
    const errorData = await response.json();
    throw new Error(
      errorData.error || `Failed to create product: ${response.statusText}`
    );
  }
  return response.json();
};

// UPDATE A Product
export const updateProduct = async (
  // The ID of the product to update.
  id: string,
  // The data to update. Partial<Product> allows for updating only some fields.
  productData: Partial<Product>,
  // The JWT token for authorization.
  token: string
): Promise<Product> => {
  const response = await fetch(`${API_BASE_URL}/api/products/${id}`, {
    method: "PUT",
    headers: {
      "Content-Type": "application/json",
      // Include the token in the Authorization header.
      Authorization: `Bearer ${token}`,
    },
    body: JSON.stringify(productData),
  });

  if (!response.ok) {
    const errorData = await response.json();
    throw new Error(
      errorData.error || `Failed to update product: ${response.statusText}`
    );
  }
  return response.json();
};

// DELETE A Product
export const deleteProduct = async (
  // The ID of the product to delete.
  id: string,
  // The JWT token for authorization.
  token: string
): Promise<Product> => {
  const response = await fetch(`${API_BASE_URL}/api/products/${id}`, {
    method: "DELETE",
    headers: {
      // Include the token in the Authorization header.
      Authorization: `Bearer ${token}`,
    },
  });

  if (!response.ok) {
    const errorData = await response.json();
    throw new Error(
      errorData.error || `Failed to delete product: ${response.statusText}`
    );
  }
  // The backend returns the deleted product, which can be useful for UI updates.
  return response.json();
};
